### PR TITLE
Method to update attributes by userid in user_attribute (API 1)

### PR DESCRIPTION
**Pull request by SRJ9**
Added method to update a list of attributes that are present in the table, passing a userid and a dictionary [{"attributeid": "value", ... }], returning all attributes of that userid even though they have not been updated. Also, through another method, you can update one attribute individually.

Also I intend to create a method for delete attributes.

### CODE REVIEW

**Comment by michield** [comment]
I can't merge this one, it has conflicts. Can you rebase and redo the PR?
thanks

**Comment by SRJ9** [comment]
Fixed.

**Comment by michield** [comment]
Thanks. I got the testing back in action https://travis-ci.org/phpList/phplist-plugin-restapi

I would be nice to add unit tests for your new methods :-)

**Comment by SRJ9** [comment]
In the following weeks I will try to make them.

**Pull request merged**
